package torreparqueadero;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : Gui.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class Gui {
	/** */
	private boolean IngresarVehiculo(String placaV, Object tipoDeVehiculo, HoraDelDia horaEstRetiroV, HoraDelDia horaIngresoV, int iDClienteV) {
	
	}
	
	/** */
	private boolean GetInfoVehiculo(int numeroReciboR) {
	
	}
	
	/** */
	private void RetirarVehiculo(int numeroReciboR) {
	
	}
}
