package torreparqueadero;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : HoraDelDia.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** Representa la hora en horas y minutos como un reloj militar,
 * es decir, siguiendo el formato de 24 horas.
 * 
 * @author Luis M Ponce de leon
 */
public class HoraDelDia {
	/** La hora representada, ignorando los minutos. 
         * Toma valores enteros entre 0 y 23.
         */
	private int horas;
	
	/** Los minutos de la hora representada.
         * Toma valores enteros entre 0 y 59
         */
	private int minutos;
	
        /** Constructor que recibe la hora y minutos en formato 24horas.
         * 
         * @param h hora a representar, sin minutos.
         * @param min minutos de la hora a representar.
         */
        public HoraDelDia(int h, int min){
            horas = h;
            minutos = min;
        }
        
	/** Retorna la hora como un string con formato: hora:minuto.
         * 
         * @return La hora almacenada como un string de la forma: 12:03
         */
	public String GetHoraEn24() {
            return "" + horas/10 + horas%10 + ":" + minutos/10 + minutos%10;
	}
	
	/** Compara la hora del dia almacenada con la que se da como parametro.
         * Retorna 1 si la recibida es mayor, 0 si es igual y -1 si es menor.
         * 
         * @param aComparar La hora recibida para comparar.
         * @return 1 si la recibida es mayor, 0 si es igual y -1 si es menor.
         */
	public int Comparar(HoraDelDia aComparar) {
            if (aComparar.horas > this.horas){
                return 1;
            } else {
                if (aComparar.horas < this.horas){
                    return -1;
                } else {
                    return 0;
                }
            }
	}
}
