package torreparqueadero;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : LogEventos.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class LogEventos {
	/** */
	private Recibo listaRecibos;
	
	/** */
	private int curNumeroRecibo;
        
        
        private static LogEventos INSTANCE = new LogEventos(); 
        
        /** 
         * constructor privado para el patron de diseño singleton.
         */
        private LogEventos(){
            
        }
        
        /** geter de la insancia del singleton.
         * 
         * @return la unica instancia de LogEventos
         */
        public static LogEventos getInstance(){
            return INSTANCE;
        }
	
	/** */
	public void CrearEvento(Vehiculo vIn, Cliente cIn, int numRecibo) {
	
	}
	
	/** */
	public Recibo BuscarRecibo(int numRecibo) {
	
	}
        
        public Recibo BuscarReciboPorPlaca(Sting placa){
            
        }
}
