package torreparqueadero;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : RelojInterno.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class RelojInterno {
	/** */
	private HoraDelDia horaActual;
	
        /**
         * @return 
         */
	public HoraDelDia GetHoraActual() {
	
	}
	
        /**
         * @param horas
         * @param minutos  
         */
	public void AdelantarTiempo(int horas, int minutos) {
	
	}
}
