package torreparqueadero;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : Cliente.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** La clase que contiene la informacion relacionada con el cliente.
 * Contiene el ID y la deuda de este.
 * 
 * @author luismiguel
 */
public class Cliente {
	/** 
         * Este sera unico y sera la manera de identificar al cliente.
         * Este sera su cedula, tarjeta de identidad
         * u otro documento de identidad.
         */
	private int iDCliente;
	
	/** 
         * La deuda que posee el cliente con el parqueadero. Esta se genera 
         * cuando el vehiculo es retirado por el sistemas a las 23:59
         */
	private int deudaAcumulada=0;
	
	/** Geter del Id del cliente
         * 
         * @return el ID del cliente como entero.
         */
	public int GetID() {
            return iDCliente;
	}
	
	/** Geter de la deuda del cliente.
         * 
         * @return La deuda como entero.
         */
	public int GetDeuda() {
            return deudaAcumulada;
	}
	
	/** Seter de la deuda del cliente.
         * 
         * @param deuda El valor que tendra la deuda del cliente.
         */
	public void SetDeuda(int deuda) {
            this.deudaAcumulada = deuda;
	}
}
