package torreparqueadero;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : LogEventos.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** Clase encargada de mantener control de todos los eventos (ingresos, retiros,
 * etc..) los que son identificados por un recibo.
 * <p>
 * Esta clase sigue el patron de diseño singleton, buscando que solo exista una
 * instancia de esta clase.
 * 
 * @author luismiguel
 */
public class LogEventos {
	/** */
	private Recibo listaRecibos;
	
	/** */
	private int curNumeroRecibo;
        
        /**
         * Unica instancia de la clase.
         */
        private static LogEventos INSTANCE = new LogEventos(); 
        
        /** 
         * constructor privado para el patron de diseño singleton.
         */
        private LogEventos(){
            
        }
        
        /** geter de la insancia del singleton.
         * 
         * @return la unica instancia de LogEventos
         */
        public static LogEventos getInstance(){
            return INSTANCE;
        }
	
	/** */
	public void CrearEvento(Vehiculo vIn, Cliente cIn, int numRecibo) {
	
	}
	
	/** */
	public Recibo BuscarRecibo(int numRecibo) {
	
	}
        
        public Recibo BuscarReciboPorPlaca(Sting placa){
            
        }
}
