//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : Cliente.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class Cliente {
	/** */
	private int iDCliente;
	
	/** */
	private int deudaAcumulada;
	
	/** */
	public int GetID() {
	
	}
	
	/** */
	public int GetDeuda() {
	
	}
	
	/** */
	public void SetDeuda(int deuda) {
	
	}
}
