//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : EntradaParqueadero.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class EntradaParqueadero {
	/** */
	private Vehiculo[] celda;
	
	/** */
	private int celdasOcupadas;
	
	/** */
	public void AgregarVehiculo(Vehiculo vIn) {
	
	}
	
	/** */
	public void RetirarVehiculo(String placa) {
	
	}
	
	/** */
	public int GetCeldasOcupadas() {
	
	}
}
