//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : HoraDelDia.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class HoraDelDia {
	/** */
	private int horas;
	
	/** */
	private int minutos;
	
	/** */
	public String GetHoraEn24() {
	
	}
	
	/** */
	public int Comparar(HoraDelDia aComparar) {
	
	}
}
