//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : LogEventos.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class LogEventos {
	/** */
	private Recibo listaRecibos;
	
	/** */
	private int curNumeroRecibo;
	
	/** */
	public void CrearEvento(Vehiculo vIn, Cliente cIn, int numRecibo) {
	
	}
	
	/** */
	public Recibo BuscarRecibo(int numRecibo) {
	
	}
}
