//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : Parqueaderos.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class Parqueaderos {
	/** */
	private EntradaParqueadero[26][10] torre;
	
	/** */
	private Vehiculo[] sotano;
	
	/** */
	private int celdasOcupadasSotano;
	
	/** */
	private int [][] matrizDeDisponibilidad;
	
	/** */
	public boolean IngresarVehiculo(Vehiculo vIn) {
	
	}
	
	/** */
	public void RetirarVehiculo(String placa) {
	
	}
	
	/** */
	public int GetCeldasSotano() {
	
	}
	
	/** */
	public void LimpiezaCeldas() {
	
	}
}
