//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : Recibo.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class Recibo {
	/** */
	private Vehiculo vehiculo;
	
	/** */
	private Cliente cliente;
	
	/** */
	private int numeroRecibo;
	
	/** */
	public void ImprimirRecibo() {
	
	}
	
	/** */
	public int GenerarCobro(HoraDelDia horaDeRetiro) {
	
	}
}
