//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : RelojInterno.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class RelojInterno {
	/** */
	private HoraDelDia horaActual;
	
	/** */
	public HoraDelDia GetHoraActual() {
	
	}
	
	/** */
	public void AdelantarTiempo(int horas, int minutos) {
	
	}
}
