//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TorreParqueadero
//  @ File Name : Vehiculo.java
//  @ Date : 04/2013
//  @ Author : Luis M Ponce de leon
//
//




/** */
public class Vehiculo {
	/** */
	private Object tipoDeVehiculo;
	
	/** */
	private String placa;
	
	/** */
	private HoraDelDia horaIngreso;
	
	/** */
	private HoraDelDia horaEstRetiro;
	
	/** */
	public HoraDelDia GetHoraEstRetiro() {
	
	}
	
	/** */
	public String GetPlaca() {
	
	}
	
	/** */
	public tipoDeVehiculo GetTipo() {
	
	}
	
	/** */
	public HoraDelDia GetHoraIngreso() {
	
	}
}
