/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Model;

/**
 *
 * @author Luis M Ponce de leon
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_StatTorre = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jPanel_SeccionIzq = new javax.swing.JPanel();
        jPanel_SeccionDer = new javax.swing.JPanel();
        jPanel_Info = new javax.swing.JPanel();
        jButton_Retiro = new javax.swing.JButton();
        jButton_Ingreso = new javax.swing.JButton();
        jTextArea_TimeProxRet = new javax.swing.JTextArea();
        jTextArea_TimeActual = new javax.swing.JTextArea();
        jTextArea_DispSotano = new javax.swing.JTextArea();
        jLabel_TitleSotano = new javax.swing.JLabel();
        jLabel_TitleProxRet = new javax.swing.JLabel();
        jLabel_TitleTimeActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        jPanel_StatTorre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Status Torre");

        jPanel_SeccionIzq.setBorder(javax.swing.BorderFactory.createTitledBorder("Seccion Superior"));

        javax.swing.GroupLayout jPanel_SeccionIzqLayout = new javax.swing.GroupLayout(jPanel_SeccionIzq);
        jPanel_SeccionIzq.setLayout(jPanel_SeccionIzqLayout);
        jPanel_SeccionIzqLayout.setHorizontalGroup(
            jPanel_SeccionIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel_SeccionIzqLayout.setVerticalGroup(
            jPanel_SeccionIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jPanel_SeccionDer.setBorder(javax.swing.BorderFactory.createTitledBorder("Seccion Inferior"));

        javax.swing.GroupLayout jPanel_SeccionDerLayout = new javax.swing.GroupLayout(jPanel_SeccionDer);
        jPanel_SeccionDer.setLayout(jPanel_SeccionDerLayout);
        jPanel_SeccionDerLayout.setHorizontalGroup(
            jPanel_SeccionDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        jPanel_SeccionDerLayout.setVerticalGroup(
            jPanel_SeccionDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_StatTorreLayout = new javax.swing.GroupLayout(jPanel_StatTorre);
        jPanel_StatTorre.setLayout(jPanel_StatTorreLayout);
        jPanel_StatTorreLayout.setHorizontalGroup(
            jPanel_StatTorreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_StatTorreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_StatTorreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_StatTorreLayout.createSequentialGroup()
                        .addComponent(jPanel_SeccionIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_SeccionDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel_StatTorreLayout.setVerticalGroup(
            jPanel_StatTorreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_StatTorreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_StatTorreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_SeccionIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_SeccionDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_Info.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_Retiro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Retiro.setText("RETIRO");
        jButton_Retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RetiroActionPerformed(evt);
            }
        });

        jButton_Ingreso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Ingreso.setText("INGRESO");
        jButton_Ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IngresoActionPerformed(evt);
            }
        });

        jTextArea_TimeProxRet.setEditable(false);
        jTextArea_TimeProxRet.setColumns(5);
        jTextArea_TimeProxRet.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jTextArea_TimeProxRet.setRows(1);
        jTextArea_TimeProxRet.setText("00:00");

        jTextArea_TimeActual.setEditable(false);
        jTextArea_TimeActual.setColumns(5);
        jTextArea_TimeActual.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jTextArea_TimeActual.setRows(1);
        jTextArea_TimeActual.setText("00:00");

        jTextArea_DispSotano.setEditable(false);
        jTextArea_DispSotano.setColumns(5);
        jTextArea_DispSotano.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jTextArea_DispSotano.setRows(1);
        jTextArea_DispSotano.setText("100");

        jLabel_TitleSotano.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_TitleSotano.setText("Status Sotano");

        jLabel_TitleProxRet.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_TitleProxRet.setText("Proximo Retiro");

        jLabel_TitleTimeActual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_TitleTimeActual.setText("Reloj Interno");

        javax.swing.GroupLayout jPanel_InfoLayout = new javax.swing.GroupLayout(jPanel_Info);
        jPanel_Info.setLayout(jPanel_InfoLayout);
        jPanel_InfoLayout.setHorizontalGroup(
            jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Retiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Ingreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_TitleSotano)
                    .addComponent(jTextArea_DispSotano, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextArea_TimeProxRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TitleProxRet)
                    .addComponent(jTextArea_TimeActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TitleTimeActual))
                .addGap(45, 45, 45))
        );
        jPanel_InfoLayout.setVerticalGroup(
            jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InfoLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel_TitleTimeActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextArea_TimeActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_TitleProxRet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea_TimeProxRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_TitleSotano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextArea_DispSotano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_StatTorre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_StatTorre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RetiroActionPerformed
        // TODO add your handling code here:
        System.out.println("Retiro");
    }//GEN-LAST:event_jButton_RetiroActionPerformed

    private void jButton_IngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IngresoActionPerformed
        // TODO add your handling code here:
        System.out.println("Ingreso");
    }//GEN-LAST:event_jButton_IngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Ingreso;
    private javax.swing.JButton jButton_Retiro;
    private javax.swing.JLabel jLabel_TitleProxRet;
    private javax.swing.JLabel jLabel_TitleSotano;
    private javax.swing.JLabel jLabel_TitleTimeActual;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JPanel jPanel_Info;
    private javax.swing.JPanel jPanel_SeccionDer;
    private javax.swing.JPanel jPanel_SeccionIzq;
    private javax.swing.JPanel jPanel_StatTorre;
    private javax.swing.JTextArea jTextArea_DispSotano;
    private javax.swing.JTextArea jTextArea_TimeActual;
    private javax.swing.JTextArea jTextArea_TimeProxRet;
    // End of variables declaration//GEN-END:variables
}
